"""Join requests

Revision ID: f0de26b19b23
Revises: 4e5682aeaa15
Create Date: 2026-04-07 00:31:17.094233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0de26b19b23'
down_revision = '4e5682aeaa15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_join_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_join_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_join_request_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_join_request_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_join_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_join_request_user_id'))
        batch_op.drop_index(batch_op.f('ix_project_join_request_project_id'))

    op.drop_table('project_join_request')
    # ### end Alembic commands ###
